# this is a config file for the real deployment of the Relay Learning to a specific clinical site
common:
  random_seed: 1314
  num_workers: 4
  dataset:
    name: fundus
    kwargs:
      task: segmentation
      num_classes: 3
      root_path: /home/user/data/fundus
      img_size: [ 64, 64 ]
      use_roi: true
      out_range: [ -1.0, 1.0 ]
      num_replica: 200
  strategy:
    name: relay
    kwargs:
      rgb_inputs: true
  model:
    name: doublegan
    kwargs:
      task: segmentation
      optimizer_conf:
        G:
          name: Adam
          kwargs:
            lr: 0.002
            betas: [ 0, 0.99199 ]
        D:
          name: Adam
          kwargs:
            lr: 0.002353
            betas: [ 0, 0.990585 ]
        M:
          name: Adam
          kwargs:
            lr: 0.001
      img_resolution: 64
      img_channels: 3
      label_num_classes: 3

      z_img_dim: 128
      z_label_dim: 64
      c_img_dim: 32
      c_label_dim: 32
      w_img_dim: 256
      w_label_dim: 128
      G_img_kwargs:
        mapping_kwargs:
          num_layers: 4
        synthesis_kwargs:
          channel_base: 8192
          channel_max: 256
      G_label_kwargs:
        mapping_kwargs:
          num_layers: 2
        synthesis_kwargs:
          channel_base: 4096
          channel_max: 128
      D_img_kwargs:
        channel_base: 8192
        channel_max: 256
      D_label_kwargs:
        channel_base: 4096
        channel_max: 128
      solver_name: U-Net
      solver_kwargs:
        in_channels: 3
        num_classes: 3
        bilinear: false
        backbone: resnet18

      num_stages: 2
      weighted_merge: true
      label_noise: 0.02
      style_mixing_prob: 0.8
      replay_w_truncation: 1.0
      replay_keep_batch_size: true
      replay_data_ratio: half
      replay_c_select_mode: uniform
      replay_post_aug: true

      G_reg_interval: 4
      D_reg_interval: 8
      pl_weight: 2
      r1_gamma: 0.1
      solver_distil_weight: 0.5

      aug_conf_img: bgcfn
      ada_target_img: 0.6
      aug_p_range_img: [ 0.0, 1.0 ]
      aug_conf_label: bg
      ada_target_label: 0.6
      aug_p_range_label: [ 0.0, 1.0 ]
      ada_interval: 4
      ada_kimg: 500
  train:
    num_mimgs: 3
    batch_size: 128
    precision: 32
    loss:
      name: ExpLogLoss
      kwargs:
        soft_dice: true
        dice_kwargs:
          do_bg: false
          batch_dice: true
        wce_kwargs:
          weight: [ 1, 2, 2 ]
        gamma: 0.3
    gradient_clip: 0.0
    check_val_every_n_epoch: 10
    log_every_n_steps: 20

# all tasks for test. Choose how many task data is accessible in this config.
all_tasks_datasets:
  - kwargs:
      task_id: 1
      task_name: Domain1
      img_folder: Domain1
# only one task at a single site.
current_tasks:
  task_ids: [ 1 ]
  task_confs:
    1:
      model:
        kwargs:
          solver_kwargs:
            pretrain: true
      checkpoint:
        load: null  # when begin another task
        resume: null  # when resume in the same task
        save:
          dir: task_1  # where to save the model, which can be relayed to the next site
